---
- hosts: vbox
  vars:
    logstashserver: 127.0.0.1
  remote_user: root

  tasks:
  - name: Enable EPEL-Release
    yum: 
        name: 
          - epel-release
        state: latest
      

  - name: Download Filebeat RPM - Package
    get_url:
        url: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.3.0-x86_64.rpm
        dest: /root/filebeat-7.3.0-x86_64.rpm
        
  - name: install local filebeat package
    yum:
        name: filebeat-7.3.0-x86_64.rpm
        state: present
        
        
  - name: "create correct filebeat config with jinjer template"  
    template: 
        src: FilebeatFiles/config/filebeat.j2
        dest: "/etc/filebeat/filebeat.yml"
        mode: '755'
  
  - name: "copy filebeat ssl files"  
    copy:
        src: "{{ item }}"
        dest: /etc/filebeat/
        mode: 5775
    with_fileglob:
    - FilebeatFiles/ssl/*    


  - name: "Start and enable Filebeat"
    systemd:
        daemon_reload: yes
        name: filebeat
        state: started
        enabled: yes