---
- hosts: vbox
  remote_user: root

  tasks:
  - name: Enable EPEL-Release
    yum: 
        name: 
          - epel-release
        state: latest
      

      
  - name: Get prerequisite software for snort
    yum:
        name:           
          - tcpdump
          - gcc 
          - flex 
          - bison 
          - zlib 
          - libpcap 
          - pcre 
          - libdnet 
          - tcpdump
          - wget
        state: latest
     
  - name: Get prerequisite software for snort build process
    yum:
        name:           
        - zlib-devel 
        - libpcap-devel 
        - pcre-devel 
        - libdnet-devel 
        - openssl-devel 
        - libnghttp2-devel 
        - luajit-devel
        - libpcap-devel

        state: latest
    
  - name: Create temp folder for sourcecode of daq and snort
    file:
        path: ~/snort_src
        state: directory
        
        
  - name: Download and extract daq
    unarchive:
        src: https://www.snort.org/downloads/snort/daq-2.0.6.tar.gz
        dest: ~/snort_src/
        remote_src: yes


  - name: configure daq
    command: ./configure 
    args:
        chdir: ~/snort_src/daq-2.0.6 
    
    
  - name: Build daq
    make:
      chdir: ~/snort_src/daq-2.0.6


  - name: install daq
    make:
      chdir: ~/snort_src/daq-2.0.6
      target: install
      
      
      
  - name: Download and extract source code for snort
    unarchive:
        src: https://www.snort.org/downloads/snort/snort-2.9.13.tar.gz
        dest: ~/snort_src/
        remote_src: yes


  - name: configure snort
    command: ./configure 
    args:
        chdir: ~/snort_src/snort-2.9.13
    
    
  - name: Build snort
    make:
      chdir: ~/snort_src/snort-2.9.13
  
  - name: install snort
    make:
      chdir: ~/snort_src/snort-2.9.13
      target: install
      
        
  #- name: create symbolic snort links
  #  command: ln -s /usr/local/bin/snort /usr/sbin/snort

  - name: Create a symbolic link
    file:
        src: /usr/local/bin/snort
        dest: /usr/sbin/snort
        state: link

  - name: Ensure group "somegroup" exists
    group:
        name: snort
        state: present
  
  - name: Add the user 'james' with a bash shell, appending the group 'admins' and 'developers' to the user's groups
    user:
        name: snort
        shell: /sbin/nologin
        groups: snort
        system: yes
        comment: SNORT_IDS
        append: yes
    
  - name: Create /etc/snort
    file:
        path: /etc/snort  
        state: directory
        recurse: yes
        mode: 5775
        owner: snort
        group: snort
    
     
  - name: Create log folder 
    file:
        path: /var/log/snort
        state: directory
        recurse: yes
        mode: 5775
        owner: snort
        group: snort
     
  - name: create snort dynamic rules
    file:
        path: /usr/local/lib/snort_dynamicrules
        state: directory
        recurse: yes
        mode: 5775
        owner: snort
        group: snort

  - name: Create rule folder
    file:
        path: /etc/snort/rules
        state: directory
        recurse: yes
        mode: 5775
        owner: snort
        group: snort

  - name: "Copy config files"  
    copy:
        src: "{{ item }}"
        dest: /etc/snort/
        owner: snort
        group: snort
        mode: 5775
    with_fileglob:
    - files/*


  - name: "Copy rules"  
    copy:
        src: "{{ item }}"
        dest: /etc/snort/rules/
        owner: snort
        group: snort
        mode: 5775
    with_fileglob:
    - files/rules/*


