---
- hosts: vbox
  vars:
    homenet: 192.168.0.0/16
  remote_user: root

  tasks:
  - name: Enable EPEL-Release
    yum: 
        name: 
          - epel-release
        state: latest
      

      
  - name: Get prerequisite software for snort
    yum:
        name:           
          - tcpdump
          - gcc 
          - flex 
          - bison 
          - zlib 
          - libpcap 
          - pcre 
          - libdnet 
          - tcpdump
          - wget
        state: latest
     
  - name: Get prerequisite software for snort build process
    yum:
        name:           
        - zlib-devel 
        - libpcap-devel 
        - pcre-devel 
        - libdnet-devel 
        - openssl-devel 
        - libnghttp2-devel 
        - luajit-devel
        - libpcap-devel

        state: latest
    
  - name: Create temp folder for sourcecode of daq and snort
    file:
        path: ~/snort_src
        state: directory
        
        
  - name: Download and extract daq
    unarchive:
        src: https://www.snort.org/downloads/snort/daq-2.0.6.tar.gz
        dest: ~/snort_src/        
        validate_certs: false
        remote_src: yes


  - name: configure daq
    command: ./configure 
    args:
        chdir: ~/snort_src/daq-2.0.6 
    
    
  - name: Build daq
    make:
      chdir: ~/snort_src/daq-2.0.6


  - name: install daq
    make:
      chdir: ~/snort_src/daq-2.0.6
      target: install
      
      
      
  - name: Download and extract source code for snort
    unarchive:
        src: https://www.snort.org/downloads/snort/snort-2.9.14.1.tar.gz
        dest: ~/snort_src/
        remote_src: yes
        validate_certs: false


  - name: configure snort
    command: ./configure 
    args:
        chdir: ~/snort_src/snort-2.9.14.1
    
    
  - name: Build snort
    make:
      chdir: ~/snort_src/snort-2.9.14.1
  
  - name: install snort
    make:
      chdir: ~/snort_src/snort-2.9.14.1
      target: install
      
        
  #- name: create symbolic snort links
  #  command: ln -s /usr/local/bin/snort /usr/sbin/snort

  - name: Create a symbolic link
    file:
        src: /usr/local/bin/snort
        dest: /usr/sbin/snort
        state: link

  - name: Ensure group "snort" exists
    group:
        name: snort
        state: present
  
  - name: Add Snort User
    user:
        name: snort
        shell: /sbin/nologin
        groups: snort
        system: yes
        comment: SNORT_IDS
        append: yes
    
  - name: Create /etc/snort
    file:
        path: /etc/snort  
        state: directory
        recurse: yes
        mode: 5775
        owner: snort
        group: snort
    
     
  - name: Create log folder 
    file:
        path: /var/log/snort
        state: directory
        recurse: yes
        mode: 5775
        owner: snort
        group: snort
     
  - name: create snort dynamic rules
    file:
        path: /usr/local/lib/snort_dynamicrules
        state: directory
        recurse: yes
        mode: 5775
        owner: snort
        group: snort

  - name: Create rule folder
    file:
        path: /etc/snort/rules
        state: directory
        recurse: yes
        mode: 5775
        owner: snort
        group: snort

  - name: "Copy snort config files"  
    copy:
        src: "{{ item }}"
        dest: /etc/snort/
        owner: snort
        group: snort
        mode: 5775
    with_fileglob:
    - SnortFiles/snortconfig/*
    
  - name: "create correct snort config with jinjer template"  
    template: 
        src: SnortFiles/snort.j2
        dest: "/etc/snort/snort.conf"
        mode: '755'


  - name: "Copy rules"  
    copy:
        src: "{{ item }}"
        dest: /etc/snort/rules/
        owner: snort
        group: snort
        mode: 5775
    with_fileglob:
    - SnortFiles/rules/*
    
  - name: "Copy snort daemon config"  
    copy:
        src: SnortFiles/snortd
        dest: /etc/init.d
        owner: root
        group: root
        mode: 755

  - name: "Start and enable Snort Daemon"
    systemd:
        daemon_reload: yes
        name: snortd
        state: started
        enabled: yes

