---
- hosts: vbox
  remote_user: root

  tasks:
  - name: Enable EPEL-Release
    yum: 
        name: 
          - epel-release
        state: latest
        
  - name: Get prerequisite software for snort
    yum:
        name:           
          - tcpdump
          - gcc 
          - flex 
          - bison 
          - zlib 
          - libpcap 
          - pcre 
          - libdnet 
          - tcpdump
          - wget
        state: latest
     
  - name: Get prerequisite software for snort build process
    yum:
        name:           
        - zlib-devel 
        - libpcap-devel 
        - pcre-devel 
        - libdnet-devel 
        - openssl-devel 
        - libnghttp2-devel 
        - luajit-devel
        - libpcap-devel
        state: latest
    
  - name: Create temp folder, containing snort 
    command: mkdir snort_src
    args:
        chdir: ~
        creates: ~/snort_src